version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Build the app!"
      - npm run build
  post_build:
    commands:
      - echo "Copy files in necessary files and folders!"
      - npm run postbuild
      - echo "Fetching certificate from S3..."
      - aws s3 cp s3://elasticbeanstalk-eu-central-1-130655165674/ca/global-bundle.pem ./dist/ca/global-bundle.pem

artifacts:
  files:
    - '**/*'
  base-directory: './dist'